version: '3.4'

services:
  examples.charge.api:
    image: ${DOCKER_REGISTRY-}pgcchargeapi
    build:
      context: .
      dockerfile: Web Charge/Examples.Charge.API/Dockerfile
    ports:
      - "5100:80"
    depends_on:
      - db
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: stefanini_mssqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Master@123
    ports:
      - "1401:1433"
    volumes:
      - stefanini-sqldata:/var/opt/mssql
volumes:
  stefanini-sqldata: