/**
 * Example Api
 * Example Charge Api.
 *
 * OpenAPI spec version: v1
 * Contact: example@example.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs/Observable';

import { ExamplesChargeApplicationMessagesRequestExampleRequest } from '../model/ExampleRequest';
import { ExamplesChargeApplicationMessagesResponseExampleListResponse } from '../model/ExampleListResponse';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class ExampleService {

    protected basePath = 'https://localhost';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (let consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * 
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public exampleGETSystemLinqEnumerableSelectListIterator2MicrosoftAspNetCoreMvcAbstractionsParameterDescriptorSystemString(observe?: 'body', reportProgress?: boolean): Observable<ExamplesChargeApplicationMessagesResponseExampleListResponse>;
    public exampleGETSystemLinqEnumerableSelectListIterator2MicrosoftAspNetCoreMvcAbstractionsParameterDescriptorSystemString(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ExamplesChargeApplicationMessagesResponseExampleListResponse>>;
    public exampleGETSystemLinqEnumerableSelectListIterator2MicrosoftAspNetCoreMvcAbstractionsParameterDescriptorSystemString(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ExamplesChargeApplicationMessagesResponseExampleListResponse>>;
    public exampleGETSystemLinqEnumerableSelectListIterator2MicrosoftAspNetCoreMvcAbstractionsParameterDescriptorSystemString(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<ExamplesChargeApplicationMessagesResponseExampleListResponse>(`${this.basePath}/api/Example`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param id 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public exampleGETSystemLinqEnumerableSelectListIterator2MicrosoftAspNetCoreMvcAbstractionsParameterDescriptorSystemString_1(id: number, observe?: 'body', reportProgress?: boolean): Observable<string>;
    public exampleGETSystemLinqEnumerableSelectListIterator2MicrosoftAspNetCoreMvcAbstractionsParameterDescriptorSystemString_1(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<string>>;
    public exampleGETSystemLinqEnumerableSelectListIterator2MicrosoftAspNetCoreMvcAbstractionsParameterDescriptorSystemString_1(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<string>>;
    public exampleGETSystemLinqEnumerableSelectListIterator2MicrosoftAspNetCoreMvcAbstractionsParameterDescriptorSystemString_1(id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling exampleGETSystemLinqEnumerableSelectListIterator2MicrosoftAspNetCoreMvcAbstractionsParameterDescriptorSystemString_1.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<string>(`${this.basePath}/api/Example/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param request 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public examplePOSTSystemLinqEnumerableSelectListIterator2MicrosoftAspNetCoreMvcAbstractionsParameterDescriptorSystemString(request?: ExamplesChargeApplicationMessagesRequestExampleRequest, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public examplePOSTSystemLinqEnumerableSelectListIterator2MicrosoftAspNetCoreMvcAbstractionsParameterDescriptorSystemString(request?: ExamplesChargeApplicationMessagesRequestExampleRequest, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public examplePOSTSystemLinqEnumerableSelectListIterator2MicrosoftAspNetCoreMvcAbstractionsParameterDescriptorSystemString(request?: ExamplesChargeApplicationMessagesRequestExampleRequest, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public examplePOSTSystemLinqEnumerableSelectListIterator2MicrosoftAspNetCoreMvcAbstractionsParameterDescriptorSystemString(request?: ExamplesChargeApplicationMessagesRequestExampleRequest, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json-patch+json',
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<any>(`${this.basePath}/api/Example`,
            request,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
