/**
 * Example Api
 * Example Charge Api.
 *
 * OpenAPI spec version: v1
 * Contact: example@example.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ExamplesChargeApplicationDtosExampleDto } from './ExampleDto';


export interface ExamplesChargeApplicationMessagesResponseExampleListResponse {
    exampleObjects?: Array<ExamplesChargeApplicationDtosExampleDto>;
    success?: boolean;
    errors?: Array<any>;
}
